export default[
  {
  "login": "deviloo7",
  "id": 51024681,
  "node_id": "MDQ6VXNlcjUxMDI0Njgx",
  "avatar_url": "https://avatars3.githubusercontent.com/u/51024681?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/deviloo7",
  "html_url": "https://github.com/deviloo7",
  "followers_url": "https://api.github.com/users/deviloo7/followers",
  "following_url": "https://api.github.com/users/deviloo7/following{/other_user}",
  "gists_url": "https://api.github.com/users/deviloo7/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/deviloo7/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/deviloo7/subscriptions",
  "organizations_url": "https://api.github.com/users/deviloo7/orgs",
  "repos_url": "https://api.github.com/users/deviloo7/repos",
  "events_url": "https://api.github.com/users/deviloo7/events{/privacy}",
  "received_events_url": "https://api.github.com/users/deviloo7/received_events",
  "type": "User",
  "site_admin": false,
  "name": null,
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 11,
  "public_gists": 0,
  "followers": 1,
  "following": 1,
  "created_at": "2019-05-25T13:36:06Z",
  "updated_at": "2020-11-21T10:40:36Z"
}
]
